markdown: redcarpet
permalink: /:categories/:year/:month/:day/:title 
auto: true
safe: false
pygments: true
port: 4001
regeneration: watch

# 个人配置
title: 松鼠闹IT的Blog
description: 前端实践者
feed:
author: 松鼠闹IT